import './globals.css'

import { Client } from 'appwrite'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const client = new Client()

client.setEndpoint('https://cloud.appwrite.io/v1').setProject('652c29a1ac0a19fec480')

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
